version: "3"

services:
  fiber_app:
    container_name: fiber_app
    build:
      dockerfile: Dockerfile
    ports:
      - ${APP_PORT}:${APP_PORT}
    environment:
      - APP_PORT=${APP_PORT}
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
  
  mysql:
    container_name: fiber_mysql
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: person
    ports:
      - ${DATABASE_PORT}:3306
    volumes:
      - mysql:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=root
      start_period: 2s
      interval: 5s
      timeout: 5s
      retries: 55
  
  redis:
    container_name: fiber_redis
    image: redis:7.0.13-alpine
    ports:
      - ${REDIS_PORT}:6379
    healthcheck:
      test: redis-cli
      interval: 2s
      timeout: 3s
      retries: 5
      start_period: 1s
    
volumes:
  mysql: